import { BaseResponse } from "../BaseResponse.model";
import { DocumentResponseData } from "./DocumentResponseData.model";
import { MerchantDocument } from "./MerchantDocument.model";
export interface ApplicationResponseData extends BaseResponse {
    object: string;
    id: string;
    name: string;
    industry: string;
    processing_type: string;
    isv_merchant_type: string | null;
    isv_process_own_transactions: string | null;
    merchant_category: string | null;
    hubspot_record_id: string | null;
    bank_account_type: string | null;
    agent_name: string;
    agent_tag_values: AgentTagValues;
    agent_id: number;
    agent_parent_id: string | null;
    agent_parent_name: string | null;
    apply_pricing_template_id: string | null;
    apply_pricing_template_name: string;
    step: string | null;
    is_copied: number;
    created_at: string;
    updated_at: string;
    status: string;
    completed: number;
    lead_status: string | null;
    hardware_shippings: string | null;
    status_id: number;
    signature_override: number;
    giact_failed_checks: number;
    electronic_signature_full_name: string | null;
    possible_duplicates: string[];
    Documents: DocumentResponseData[] | null;
    bank_number: string | null;
    lead_id: string | null;
    signed_upload_url: string | null;
    adobe_agreement_id: string | null;
    docusign_agreement_envelope_id: string | null;
    agreement_status: string | null;
    date_leaded: string | null;
    ach_transactions_yn: number | null;
    storagePit: string | null;
    discount_rate_program: string | null;
    vartsq: string | null;
    MerchantContactFirstName: string | null;
    MerchantContactLastName: string | null;
    MerchantContactEmail: string | null;
    MerchantLegalName: string | null;
    MerchantOfficeAddress: string | null;
    MerchantOfficeCity: string | null;
    MerchantOfficeState: string | null;
    MerchantOfficeZipCode: string | null;
    MerchantRegisteredAddress: string | null;
    MerchantRegisteredCity: string | null;
    MerchantRegisteredState: string | null;
    MerchantRegisteredZipCode: string | null;
    merchant_ssn: string | null;
    merchant_other_tax_id: string | null;
    MerchantContactPhoneNo: string | null;
    merchant_identification_number_type: string | null;
    merchant_foundation_date: string | null;
    MerchantTaxId: string | null;
    MerchantDateIncorporated: string | null;
    MerchantStateOfIncorporation: string | null;
    MerchantOwnershipType: string | null;
    MerchantWebsite: string | null;
    MerchantCustomerSupportNumber: string | null;
    merchant_irs_filing_type: string | null;
    MerchantBusinessSummary: string | null;
    MerchantAccountUpdater: string | null;
    MerchantMinMonthlyFee: string | null;
    MerchantMonthlyFee: string | null;
    MerchantPciFee: string | null;
    MerchantTerminalFee: string | null;
    MerchantGatewayFee: string | null;
    MerchantStatementFee: string | null;
    MerchantRiskAnalysisFee: string | null;
    MerchantWebMonitoringFee: string | null;
    MerchantBankSponsorFee: string | null;
    MerchantAmexSponsorFee: string | null;
    MerchantBatchFee: string | null;
    MerchantChargebackFee: string | null;
    MerchantChargebackReversalFee: string | null;
    MerchantRetrievalFee: string | null;
    MerchantArbitrationFee: string | null;
    MerchantVoiceAuthFee: string | null;
    MerchantDebitCardAuthsFee: string | null;
    MerchantEbtAuthsFee: string | null;
    MerchantAccountUpdateOtherFee: string | null;
    MerchantGatewayTransactionsFee: string | null;
    MerchantPerAchRejectFee: string | null;
    MerchantDeclinesFee: string | null;
    MerchantRefundsFee: string | null;
    MerchantAvsFee: string | null;
    MerchantEthocaVerifiAlertsFee: string | null;
    MerchantRapidDisputeResolutionFee: string | null;
    MerchantCurrentlyAcceptCreditCards: string | null;
    MerchantCardPresentPct: string | null;
    MerchantMotoPct: string | null;
    MerchantBankAccountNo: string | null;
    MerchantBankRoutingNo: string | null;
    merchant_bank_name: string | null;
    merchant_account_address: string | null;
    merchant_account_city: string | null;
    merchant_account_state: string | null;
    merchant_account_zip_code: string | null;
    MerchantTotalMonthlyProcessing: string | null;
    SalesAnnualMastercard: string | null;
    SalesDeliveryOffer: string;
    SalesDeliveryDays: string | null;
    SalesDeliveryDays0Pct: string | null;
    SalesDeliveryDays1Pct: string | null;
    SalesDeliveryDays8Pct: string | null;
    SalesDeliveryDays15Pct: string | null;
    SalesDeliveryDays30Pct: string | null;
    SalesKeyedInternetPct: string | null;
    SalesKeyedMailPct: string | null;
    SalesKeyedPhonePct: string | null;
    SalesTradeshowPct: string | null;
    SalesTotalAnnual: string | null;
    SalesB2BPct: string | null;
    SalesB2CPct: string | null;
    SalesCardB2BPct: string | null;
    SalesCardB2CPct: string | null;
    SalesProductServices: string;
    MerchantAvgTicketValue: string | null;
    MerchantHighTicketValue: string | null;
    MerchantDesiredDescriptor: string | null;
    MerchantEbtFnsNumber: string | null;
    MerchantProcessingTerminated: string | null;
    MerchantBankruptcy: string | null;
    MerchantAmexProcessingPerYear: string | null;
    MerchantOtherFee: string | null;
    MerchantOtherFeeName: string | null;
    MerchantCommentsOther: string | null;
    MerchantMonthlyOtherFee: string | null;
    MerchantMonthlyOtherFeeName: string | null;
    MerchantAmexEsaNumber: string | null;
    TieredPricingQualifiedPctVisaMC: string | null;
    TieredPricingQualifiedPctAmex: string | null;
    TieredPricingQualifiedPctDiscover: string | null;
    TieredPricingQualifiedPctDebit: string | null;
    TieredPricingMidQualifiedPctVisaMC: string | null;
    TieredPricingMidQualifiedPctAmex: string | null;
    TieredPricingMidQualifiedPctDiscover: string | null;
    TieredPricingMidQualifiedPctDebit: string | null;
    TieredPricingNonQualifiedPctVisaMC: string | null;
    TieredPricingNonQualifiedPctAmex: string | null;
    TieredPricingNonQualifiedPctDiscover: string | null;
    TieredPricingNonQualifiedPctDebit: string | null;
    TieredPricingQualifiedAuthVisaMC: string | null;
    TieredPricingQualifiedAuthAmex: string | null;
    TieredPricingQualifiedAuthDiscover: string | null;
    TieredPricingQualifiedAuthDebit: string | null;
    TieredPricingMidQualifiedAuthVisaMC: string | null;
    TieredPricingMidQualifiedAuthAmex: string | null;
    TieredPricingMidQualifiedAuthDiscover: string | null;
    TieredPricingMidQualifiedAuthDebit: string | null;
    TieredPricingNonQualifiedAuthVisaMC: string | null;
    TieredPricingNonQualifiedAuthAmex: string | null;
    TieredPricingNonQualifiedAuthDiscover: string | null;
    TieredPricingNonQualifiedAuthDebit: string | null;
    InterchangePlusPricingPctVisaMC: string | null;
    InterchangePlusPricingPctAmex: string | null;
    InterchangePlusPricingPctDiscover: string | null;
    InterchangePlusAuthorizationsVisaMC: string | null;
    InterchangePlusAuthorizationsAmex: string | null;
    InterchangePlusAuthorizationsDiscover: string | null;
    BlendedRatePricingFlatRatePct: string | null;
    BlendedRatePricingAuthorizations: string | null;
    BlendedRatePricingCashDiscountRatePct: string | null;
    BlendedRatePricingCashDiscountFee: string | null;
    BlendedBaseCharge: string | null;
    BlendedPercentageCharge: string | null;
    AmexOptBlue: string | null;
    AmexBaseCharge: string | null;
    AmexPercentageCharge: string | null;
    WeeklyFee: string | null;
    MonthlyFee: string | null;
    DailyFee: string | null;
    ChargebackFee: string | null;
    ChargebackPercFee: string | null;
    FiservDiscountRateFeePct: string | null;
    FiservTransactionFee: string | null;
    FiservMonthlySplitFundingFee: string | null;
    FiservGatewayMonthlyFee: string | null;
    FiservGatewayTransactionFee: string | null;
    FiservGatewayTransactionFeePct: string | null;
    FiservAmexSponsorFeePct: string | null;
    FiservBatchFee: string | null;
    FiservSplitFundingFee: string | null;
    FiservTokenizationFee: string | null;
    FiservMonthlyMinimumFee: string | null;
    QuestionnaireAdvancedDeposits: string | null;
    QuestionnaireCaptureCVV: string | null;
    QuestionnaireDepositPct: string | null;
    QuestionnaireIsDeliveryReceiptRequested: string | null;
    QuestionnaireIsProcessingSeasonal: string | null;
    QuestionnaireMembershipPayments: string | null;
    QuestionnaireMembershipPaymentsPct: string | null;
    QuestionnaireNoRefundsInfo: string | null;
    QuestionnaireOrderTurnaroundTime: string | null;
    QuestionnairePackageUsageTime: string | null;
    QuestionnaireProcessingSeasonalMonths: string[];
    QuestionnaireProdSoldEuropePct: string | null;
    QuestionnaireProdSoldNorthAmericaPct: string | null;
    QuestionnaireProdSoldOtherMarketsPct: string | null;
    QuestionnaireRecurringPaymentProvider: string | null;
    QuestionnaireReturnPolicy: string | null;
    QuestionnaireReturnPolicyOther: string | null;
    QuestionnaireSellBusinessPct: string | null;
    QuestionnaireSellConsumerPct: string | null;
    QuestionnaireWhenIsCustomerCharged: string | null;
    QuestionnaireWhoManagesRecurringPayments: string | null;
    retrive?: () => Promise<BaseResponse | null>;
    addDocument?: (document: MerchantDocument) => Promise<BaseResponse | null>;
    submit?: () => Promise<BaseResponse | null>;
    delete?: () => Promise<BaseResponse | null>;
    update?: (appData: Record<string, any>) => Promise<BaseResponse | null>;
    listSubAgents?: () => Promise<BaseResponse | null>;
}

export interface AgentTagValues {
    id: number;
    category: string;
    item: string;
    color: string;
    agent_id: string | null;
    user_id: string | null;
    created_at: string | null;
    updated_at: string | null;
}