import { BaseResponse } from '../BaseResponse.model';
import { ListBaseResponse } from '../ListBaseResponse.model';
export interface DisputeCasesResponseData extends BaseResponse {
    object: string;
    id: string;
    full_reason_code: string;
    item_type: string;
    merchant_number: string;
    resolution_to: string | null;
    debit_credit: string;
    trans_code: string;
    reason_code: string;
    bin_ica: string;
    record_type: string;
    card_brand: string;
    date_resolved: string | null;
    acquirer_reference_number: string;
    original_reference_number: string | null;
    foreign_domestic: string;
    mcc: string | null;
    auth_code: string;
    date_posted: string;
    date_loaded: string;
    date_second_request: any;
    card_number_prefix: string;
    card_last4: string;
    merchant_dba_name: string;
    merchant_address1: any;
    merchant_address2: any;
    merchant_city: string;
    merchant_state: string;
    merchant_zip: string;
    group: string;
    tsys_bank_number: string;
    tsys_association: string;
    tsys_space: string;
    date_warehouse: string;
    transaction_id: string;
    merchant_amount: number;
    family_id: string;
    created_at: string;
    updated_at: string;
    chargeback_reference_number: string;
    mcomm_claim_id: string;
    vrol_case_number: string;
    fingerprint: string;
    log_id: number;
    bank_number: number;
    case_submitted: boolean;
    tsys_fiserv_indicator: string;
    latest_secondary_case_id: number | null;
    rdr_indicator: number;
    report_date: string;
    case_number: string;
    is_primary_case: boolean;
    transaction_date: string;
    case_amount: number;
    reason_desc: string;
    case_type: string;
    status: string;
    card_type: string;
    card_number: string;
    response: string;
    last_updated_date: string | null;
    responded_date: string | null;
    file: ListBaseResponse | null;
    evidence: ListBaseResponse | null;
    case_submission: ListBaseResponse | null;
}